### ISSUE TITLE
Übersicht Funktionalität fertigstellen

### ISSUE THREAD

**Issue by clemens29** [TillmannKrebs0/WhatToEat#11]
- [x] Favoriten Button hinzufügen (für jede MealCard, + neue Kategorie)
- [x] #13
- [x] MealCard bearbeiten (als Swipe mit Popup)
- [x] Wenn keine Dauer angegeben, dann Strich/Keine Angabe

**Comment by TillmannKrebs0** [comment]
bei der Swipe funktionalität:
wenn das mit der Seitennavigation nicht klappt, dann kannst du diese auch wieder entfernen.
Man kann die Navigtion nicht wirklich schön machen, also nehmen wir das evtl auch sowieso raus

**Comment by clemens29** [comment]
habe für das löschen und bearbeiten jetzt die id bei den Meals wieder hinzugefügt, damit macht es sich um einiges einfacher
