### ISSUE TITLE
Vue aneignen

### ISSUE THREAD

**Issue by TillmannKrebs0** [TillmannKrebs0/WhatToEat#2]
Vue anschauen und schonmal vertraut machen.
Am besten mal ein eigenes Projekt erstellen und bisschen rumprobieren

https://vuejs.org/guide/introduction.html

**Comment by clemens29** [comment]
Würde mir mittwochs dieses Video dazu anschauen, dann sollte ich die Basics drin haben :)
https://www.youtube.com/watch?v=UDWfize-zIE&t=699s
