### ISSUE TITLE
[P10+] Nur Composition API benutzen

### ISSUE THREAD

**Issue by clemens29** [TillmannKrebs0/WhatToEat#26]
Quest:

       [P10+] In Composition We Trust: Vue's Greatest Hits
        Difficulty: Hard
        Only use the syntax of the “Composition” API.

**Comment by TillmannKrebs0** [comment]
haben wir eigentlich 
(wenn ich das richtig verstanden habe dann ist composition, dass man die `<script setup>` statt nur `<setup>`)
Wusste aber noch nicht ob wir das schon abgeben können wenn wir noch in der Entwicklung sind

**Comment by clemens29** [comment]
ok, dann schließ ich den Issue mal :)
